# Generated by Django 3.1.1 on 2020-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20201114_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
