# Generated by Django 3.1.1 on 2020-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20201114_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
