# Generated by Django 3.1.1 on 2021-01-04 10:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20201114_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
